### PR TITLE
Add property and functions

### PR DESCRIPTION
**Pull request by te-deum**
Message pour Pull Request :
Hello,

I am using your plugin. It work great but for my project I need some other functionnality. So I added them.
They are :
- Possibility to translate columns filters options (_columnFilterLang_). If one or more translation is not available, English will be used by default.
- Function to get filtered rows (_getFilteredRows_)
- Functions to save and load datatable state in local storage (_saveState(name)_ + _loadState(name)_)

Here is an example of columnFilterLang translation :
```javascript
{
    'contain': 'Contiens',
    'end_with': 'Termine par',
    'equal': 'Egale',
    'greater_than': 'Supérieur à',
    'greater_than_equal': 'Sup. ou égale à',
    'is_null': 'Est null',
    'less_than': 'Inférieur à',
    'less_than_equal': 'Inf. ou égale à',
    'no_filter': 'Aucun',
    'not_contain': 'Ne contiens pas',
    'not_equal': 'Différent',
    'is_not_null': 'Non null',
    'start_with': 'Commence par',
}
```

### CODE REVIEW

**Comment by bhaveshpatel200** [comment]
Thanks, I will check on this weekend and if any changes will let you know.

I think am not agree to add saveState and LoadState functions, because you can manage this outside table package easily. same code you can write in your page and used to maintain all variables like filters, search etc read from local storage and assign.
I have already did this type state management in aggrid from outside of aggrid datatable.

**Comment by te-deum** [comment]
Hello,

I agree that it's possible to save and load state outside but not all infos are available or up to date outside (like page number, page size, sorting column and order for example). Or I may not know how to get these informations outside the plugin (If you have advise to get these infos outside).

The main purpose is to offer the possibility to save and load state out of the box without "effort".

**Comment by bhaveshpatel200** [comment]
image

we have events which are the triggers when changed page, pagesize, sorting etc, so you can manage all your variables updated based on this events.

and we can add one more method to get all params like you want to save on localstorage and can easily get all at one place.

**Comment by te-deum** [comment]
Hello,

When do you think you'll have time to check this pull request?
I would like to integrate these changes to my project.

Thank you.

**Comment by bhaveshpatel200** [comment]
Hi,
Sorry i was away. can you please remove manage datatable state in localstorage and create a new pull request.
once this done i will sure to check and update till this weekends.

**Comment by bhaveshpatel200** [comment]
Hi,

You can closed this pull request. 
I have uploaded your above changes (new props and getFilteredRows method) in new version.

**Comment by te-deum** [comment]
Thank you.

**Pull request closed without merging**
